name: 收集整合网上IPTV Sources

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时运行一次
  workflow_dispatch:  # 允许手动触发
  push:
    branches: [ main ]
    paths:
      - '**.py'
      - 'config.json'
      - '.github/workflows/update.yml'

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # 获取完整历史
      
    - name: 设置Python环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: 安装FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
        
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: 运行更新脚本
      run: |
        python main.py
        
    - name: 提交更新
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/output/
        git diff --quiet && git diff --staged --quiet || git commit -m "自动更新IPTV直播源 $(date +'%Y-%m-%d %H:%M:%S')"
        
    - name: 拉取最新更改
      run: |
        git pull --no-rebase origin main
        
    - name: 推送更新
      run: |
        git push origin main
